# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad927e8f0600bc3ca5644f79444e5f9d1f256e1acee06283c5995318987ea4878825c011901d093b9a6f223306a86431785576841d8769875a7f76c120d56e2c

test:
  secret_key_base: 6e5b0294886f0777f9e20d02dd10a5112ae49e1f1faa5feadd26b342a72a1270231f85bdbdda6b58dbf80aa9c26d2cabbdf10e34c75a4f638cd040d54cc7d518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
